import os
from urllib.parse import quote

from dotenv import load_dotenv

load_dotenv()

ENV = os.getenv("BOOK_MANAGEMENT_ENV", default="DEV")
PORT = int(os.getenv("BOOK_MANAGEMENT_PORT", default="8000"))
SERVER_URL = os.getenv("SERVER_URL", default="http://localhost:8000")

# DB
DB_NAME = os.getenv("BOOK_MANAGEMENT_DB_NAME")
DB_USER = os.getenv("BOOK_MANAGEMENT_DB_USER")
DB_PASSWORD = quote(os.getenv("BOOK_MANAGEMENT_DB_PASSWORD"))
DB_HOST = os.getenv("BOOK_MANAGEMENT_DB_HOST")
DB_PORT = int(os.getenv("BOOK_MANAGEMENT_DB_PORT"))

DATABASE_URL = (
    f"postgresql+asyncpg://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
)

# JWT
JWT_SECRET_KEY: str = os.getenv("JWT_SECRET_KEY")
JWT_ALGORITHM: str = os.getenv("JWT_ALGORITHM")
ACCESS_TOKEN_EXPIRE_MINUTES: int = int(os.getenv("ACCESS_TOKEN_EXPIRE_MINUTES"))
REFRESH_TOKEN_EXPIRE_DAYS: int = int(os.getenv("REFRESH_TOKEN_EXPIRE_DAYS", "7"))
REFRESH_TOKEN_LENGTH: int = 64

# SCHEMA
AUTH_SCHEMA = os.getenv("BOOK_MANAGEMENT_AUTH_SCHEMA", default="auth")
BOOK_SCHEMA = os.getenv("BOOK_MANAGEMENT_BOOK_SCHEMA", default="book")
COMMERCE_SCHEMA = os.getenv("BOOK_MANAGEMENT_COMMERCE_SCHEMA", default="commerce")


# TABLE
USER_TABLE = os.getenv("BOOK_MANAGEMENT_USER_TABLE")
AUTHOR_TABLE = os.getenv("BOOK_MANAGEMENT_AUTHOR_TABLE")
BOOK_TABLE = os.getenv("BOOK_MANAGEMENT_BOOK_TABLE")
CATEGORY_TABLE = os.getenv("BOOK_MANAGEMENT_CATEGORY_TABLE")
PASSWORD_RESET_TABLE = os.getenv("BOOK_MANAGEMENT_PASSWORD_RESET_TABLE")
REFRESH_TOKEN_TABLE = os.getenv("BOOK_MANAGEMENT_REFRESH_TOKEN_TABLE", "refresh_tokens")
CART_ITEMS_TABLE = os.getenv("BOOK_MANAGEMENT_CART_ITEMS_TABLE")
CART_TABLE = os.getenv("BOOK_MANAGEMENT_CART_TABLE")
ORDER_TABLE = os.getenv("BOOK_MANAGEMENT_ORDER_TABLE")
ORDER_ITEMS_TABLE = os.getenv("BOOK_MANAGEMENT_ORDER_ITEMS_TABLE")
PAYMENT_TABLE = os.getenv("BOOK_MANAGEMENT_PAYMENT_TABLE")


# MAIL
MAIL_USERNAME: str = os.getenv("MAIL_USERNAME")
MAIL_PASSWORD: str = os.getenv("MAIL_PASSWORD")
MAIL_FROM: str = os.getenv("MAIL_FROM")
MAIL_PORT: int = int(os.getenv("MAIL_PORT", "587"))
MAIL_SERVER: str = os.getenv("MAIL_SERVER", "smtp.gmail.com")
MAIL_STARTTLS: bool = os.getenv("MAIL_TLS", "True") == "True"
MAIL_SSL_TLS: bool = os.getenv("MAIL_SSL", "False") == "True"

# MinIO
MINIO_HOST = os.getenv("BOOK_MANAGEMENT_MINIO_HOST")
MINIO_ACCESS_KEY = os.getenv("BOOK_MANAGEMENT_MINIO_ACCESS_KEY")
MINIO_SECRET_KEY = os.getenv("BOOK_MANAGEMENT_MINIO_SECRET_KEY")
MINIO_REGION = os.getenv("BOOK_MANAGEMENT_MINIO_REGION")
MINIO_BUCKET = os.getenv("BOOK_MANAGEMENT_MINIO_PI_BUCKET")
